codon_table = {
    "uuu": "f", "uuc": "f",
    "uua": "l", "uug": "l",
    "cuu": "l", "cuc": "l", "cua": "l", "cug": "l",
    "auu": "i", "auc": "i", "aua": "i",
    "aug": "m",
    "guu": "v", "guc": "v", "gua": "v", "gug": "v",
    "ucu": "s", "ucc": "s", "uca": "s", "ucg": "s",
    "agu": "s", "agc": "s",
    "ccu": "p", "ccc": "p", "cca": "p", "ccg": "p",
    "acu": "t", "acc": "t", "aca": "t", "acg": "t",
    "gcu": "a", "gcc": "a", "gca": "a", "gcg": "a",
    "uau": "y", "uac": "y",
    "cau": "h", "cac": "h",
    "caa": "q", "cag": "q",
    "aau": "n", "aac": "n",
    "aaa": "k", "aag": "k",
    "gau": "d", "gac": "d",
    "gaa": "e", "gag": "e",
    "ugu": "c", "ugc": "c",
    "ugg": "w",
    "cgu": "r", "cgc": "r", "cga": "r", "cgg": "r",
    "aga": "r", "agg": "r",
    "ggu": "g", "ggc": "g", "gga": "g", "ggg": "g",
    "uaa": "stop", "uag": "stop", "uga": "stop"
}