residue_data = {
    "a": {
        "Name": "Alanine",
        "Molecular Weight": 89.09,
        "Estimated Average Hydrophobicity": 1.80,
        "pI": 6.11,
    },
    "r": {
        "Name": "Arginine",
        "Molecular Weight": 174,
        "Estimated Average Hydrophobicity": -4.50,
        "pI": 10.76,
    },
    "n": {
        "Name": "Asparagine",
        "Molecular Weight": 132.12,
        "Estimated Average Hydrophobicity": -3.50,
        "pI": 5.43,
    },
    "d": {
        "Name": "Aspartic Acid",
        "Molecular Weight": 133.10,
        "Estimated Average Hydrophobicity": -3.50,
        "pI": 2.98,
    },
    "c": {
        "Name": "Cysteine",
        "Molecular Weight": 121.16,
        "Estimated Average Hydrophobicity": 2.50,
        "pI": 5.15,
    },
    "q": {
        "Name": "Glutamine",
        "Molecular Weight": 146.14,
        "Estimated Average Hydrophobicity": -3.50,
        "pI": 5.65,
    },
    "e": {
        "Name": "Glutamic Acid",
        "Molecular Weight": 147.13,
        "Estimated Average Hydrophobicity": -3.50,
        "pI": 3.08,
    },
    "g": {
        "Name": "Glycine",
        "Molecular Weight": 75.07,
        "Estimated Average Hydrophobicity": -0.40,
        "pI": 6.06,
    },
    "h": {
        "Name": "Histidine",
        "Molecular Weight": 155.15,
        "Estimated Average Hydrophobicity": -3.20,
        "pI": 7.64,
    },
    "i": {
        "Name": "Isoleucine",
        "Molecular Weight": 131.17,
        "Estimated Average Hydrophobicity": 4.50,
        "pI": 6.04,
    },
    "l": {
        "Name": "Leucine",
        "Molecular Weight": 131.17,
        "Estimated Average Hydrophobicity": 3.80,
        "pI": 6.04,
    },
    "k": {
        "Name": "Lysine",
        "Molecular Weight": 146.19,
        "Estimated Average Hydrophobicity": -3.90,
        "pI": 9.47,
    },
    "m": {
        "Name": "Methionine",
        "Molecular Weight": 149.21,
        "Estimated Average Hydrophobicity": 1.90,
        "pI": 5.71,
    },
    "f": {
        "Name": "Phenylalanine",
        "Molecular Weight": 165.19,
        "Estimated Average Hydrophobicity": 2.80,
        "pI": 5.76,
    },
    "p": {
        "Name": "Proline",
        "Molecular Weight": 115.13,
        "Estimated Average Hydrophobicity": -1.60,
        "pI": 6.30,
    },
    "s": {
        "Name": "Serine",
        "Molecular Weight": 105.09,
        "Estimated Average Hydrophobicity": -0.80,
        "pI": 5.70,
    },
    "t": {
        "Name": "Threonine",
        "Molecular Weight": 119.12,
        "Estimated Average Hydrophobicity": -0.70,
        "pI": 5.60,
    },
    "w": {
        "Name": "Tryptophan",
        "Molecular Weight": 204.23,
        "Estimated Average Hydrophobicity": -0.90,
        "pI": 5.88,
    },
    "y": {
        "Name": "Tyrosine",
        "Molecular Weight": 181.19,
        "Estimated Average Hydrophobicity": -1.30,
        "pI": 5.63,
    },
    "v": {
        "Name": "Valine",
        "Molecular Weight": 117.15,
        "Estimated Average Hydrophobicity": 4.20,
        "pI": 6.02,
    },
}